#!/bin/bash

# loading all hooks helper
source ./hooks/bin/loader.sh

# get all modified files array
FILES=$(git_modified_files)

display inspect

# check for merge tags against all files
./hooks/src/check-merge-tags.sh ${FILES}
[[ $? -ne 0 ]] && exit 1

# check for console.log against JS/TS files
./hooks/src/check-console-log.sh ${FILES}
[[ $? -ne 0 ]] && exit 1

Ts=$(git_modified_files_by_ext "ts")

TSLINT=0
if [[ "$Ts" != "" ]]
then
    display tslint && \
    ./front/node_modules/tslint/bin/tslint --config front/tslint.json ${Ts} && \
    display success "Javascript syntax checked"

    TSLINT=$?
fi

if [[ ${TSLINT} -ne 0 ]]
then
    # display fix your code smile
    exit 1
fi

# Post checkup validation
display final && \
./hooks/src/ask-validation.sh ${FILES}
exit $?
